/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EksamenRouteImport } from './routes/eksamen'
import { Route as KunnskapskartRouteImport } from './routes/kunnskapskart'
import { Route as OppgaverRouteImport } from './routes/oppgaver'
import { Route as ProgrammeringRouteImport } from './routes/programmering'
import { Route as RessurserRouteImport } from './routes/ressurser'
import { Route as EksamenIndexRouteImport } from './routes/eksamen.index'
import { Route as EksamenExamIdRouteImport } from './routes/eksamen.$examId'
import { Route as OppgaverIndexRouteImport } from './routes/oppgaver.index'
import { Route as OppgaverKapIdRouteImport } from './routes/oppgaver.$kapId'
import { Route as OppgaverKapIdIndexRouteImport } from './routes/oppgaver.$kapId.index'
import { Route as OppgaverKapIdSubIdRouteImport } from './routes/oppgaver.$kapId.$subId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EksamenRoute = EksamenRouteImport.update({
  id: '/eksamen',
  path: '/eksamen',
  getParentRoute: () => rootRouteImport,
} as any)
const KunnskapskartRoute = KunnskapskartRouteImport.update({
  id: '/kunnskapskart',
  path: '/kunnskapskart',
  getParentRoute: () => rootRouteImport,
} as any)
const OppgaverRoute = OppgaverRouteImport.update({
  id: '/oppgaver',
  path: '/oppgaver',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammeringRoute = ProgrammeringRouteImport.update({
  id: '/programmering',
  path: '/programmering',
  getParentRoute: () => rootRouteImport,
} as any)
const RessurserRoute = RessurserRouteImport.update({
  id: '/ressurser',
  path: '/ressurser',
  getParentRoute: () => rootRouteImport,
} as any)
const EksamenIndexRoute = EksamenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EksamenRoute,
} as any)
const EksamenExamIdRoute = EksamenExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => EksamenRoute,
} as any)
const OppgaverIndexRoute = OppgaverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OppgaverRoute,
} as any)
const OppgaverKapIdRoute = OppgaverKapIdRouteImport.update({
  id: '/$kapId',
  path: '/$kapId',
  getParentRoute: () => OppgaverRoute,
} as any)
const OppgaverKapIdIndexRoute = OppgaverKapIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OppgaverKapIdRoute,
} as any)
const OppgaverKapIdSubIdRoute = OppgaverKapIdSubIdRouteImport.update({
  id: '/$subId',
  path: '/$subId',
  getParentRoute: () => OppgaverKapIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/eksamen': typeof EksamenRouteWithChildren
  '/kunnskapskart': typeof KunnskapskartRoute
  '/oppgaver': typeof OppgaverRouteWithChildren
  '/programmering': typeof ProgrammeringRoute
  '/ressurser': typeof RessurserRoute
  '/eksamen/$examId': typeof EksamenExamIdRoute
  '/oppgaver/$kapId': typeof OppgaverKapIdRouteWithChildren
  '/eksamen/': typeof EksamenIndexRoute
  '/oppgaver/': typeof OppgaverIndexRoute
  '/oppgaver/$kapId/$subId': typeof OppgaverKapIdSubIdRoute
  '/oppgaver/$kapId/': typeof OppgaverKapIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kunnskapskart': typeof KunnskapskartRoute
  '/programmering': typeof ProgrammeringRoute
  '/ressurser': typeof RessurserRoute
  '/eksamen/$examId': typeof EksamenExamIdRoute
  '/eksamen': typeof EksamenIndexRoute
  '/oppgaver': typeof OppgaverIndexRoute
  '/oppgaver/$kapId/$subId': typeof OppgaverKapIdSubIdRoute
  '/oppgaver/$kapId': typeof OppgaverKapIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/eksamen': typeof EksamenRouteWithChildren
  '/kunnskapskart': typeof KunnskapskartRoute
  '/oppgaver': typeof OppgaverRouteWithChildren
  '/programmering': typeof ProgrammeringRoute
  '/ressurser': typeof RessurserRoute
  '/eksamen/$examId': typeof EksamenExamIdRoute
  '/oppgaver/$kapId': typeof OppgaverKapIdRouteWithChildren
  '/eksamen/': typeof EksamenIndexRoute
  '/oppgaver/': typeof OppgaverIndexRoute
  '/oppgaver/$kapId/$subId': typeof OppgaverKapIdSubIdRoute
  '/oppgaver/$kapId/': typeof OppgaverKapIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/eksamen'
    | '/kunnskapskart'
    | '/oppgaver'
    | '/programmering'
    | '/ressurser'
    | '/eksamen/$examId'
    | '/oppgaver/$kapId'
    | '/eksamen/'
    | '/oppgaver/'
    | '/oppgaver/$kapId/$subId'
    | '/oppgaver/$kapId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kunnskapskart'
    | '/programmering'
    | '/ressurser'
    | '/eksamen/$examId'
    | '/eksamen'
    | '/oppgaver'
    | '/oppgaver/$kapId/$subId'
    | '/oppgaver/$kapId'
  id:
    | '__root__'
    | '/'
    | '/eksamen'
    | '/kunnskapskart'
    | '/oppgaver'
    | '/programmering'
    | '/ressurser'
    | '/eksamen/$examId'
    | '/oppgaver/$kapId'
    | '/eksamen/'
    | '/oppgaver/'
    | '/oppgaver/$kapId/$subId'
    | '/oppgaver/$kapId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EksamenRoute: typeof EksamenRouteWithChildren
  KunnskapskartRoute: typeof KunnskapskartRoute
  OppgaverRoute: typeof OppgaverRouteWithChildren
  ProgrammeringRoute: typeof ProgrammeringRoute
  RessurserRoute: typeof RessurserRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksamen': {
      id: '/eksamen'
      path: '/eksamen'
      fullPath: '/eksamen'
      preLoaderRoute: typeof EksamenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunnskapskart': {
      id: '/kunnskapskart'
      path: '/kunnskapskart'
      fullPath: '/kunnskapskart'
      preLoaderRoute: typeof KunnskapskartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oppgaver': {
      id: '/oppgaver'
      path: '/oppgaver'
      fullPath: '/oppgaver'
      preLoaderRoute: typeof OppgaverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmering': {
      id: '/programmering'
      path: '/programmering'
      fullPath: '/programmering'
      preLoaderRoute: typeof ProgrammeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ressurser': {
      id: '/ressurser'
      path: '/ressurser'
      fullPath: '/ressurser'
      preLoaderRoute: typeof RessurserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eksamen/': {
      id: '/eksamen/'
      path: '/'
      fullPath: '/eksamen/'
      preLoaderRoute: typeof EksamenIndexRouteImport
      parentRoute: typeof EksamenRoute
    }
    '/eksamen/$examId': {
      id: '/eksamen/$examId'
      path: '/$examId'
      fullPath: '/eksamen/$examId'
      preLoaderRoute: typeof EksamenExamIdRouteImport
      parentRoute: typeof EksamenRoute
    }
    '/oppgaver/': {
      id: '/oppgaver/'
      path: '/'
      fullPath: '/oppgaver/'
      preLoaderRoute: typeof OppgaverIndexRouteImport
      parentRoute: typeof OppgaverRoute
    }
    '/oppgaver/$kapId': {
      id: '/oppgaver/$kapId'
      path: '/$kapId'
      fullPath: '/oppgaver/$kapId'
      preLoaderRoute: typeof OppgaverKapIdRouteImport
      parentRoute: typeof OppgaverRoute
    }
    '/oppgaver/$kapId/': {
      id: '/oppgaver/$kapId/'
      path: '/'
      fullPath: '/oppgaver/$kapId/'
      preLoaderRoute: typeof OppgaverKapIdIndexRouteImport
      parentRoute: typeof OppgaverKapIdRoute
    }
    '/oppgaver/$kapId/$subId': {
      id: '/oppgaver/$kapId/$subId'
      path: '/$subId'
      fullPath: '/oppgaver/$kapId/$subId'
      preLoaderRoute: typeof OppgaverKapIdSubIdRouteImport
      parentRoute: typeof OppgaverKapIdRoute
    }
  }
}

interface EksamenRouteChildren {
  EksamenExamIdRoute: typeof EksamenExamIdRoute
  EksamenIndexRoute: typeof EksamenIndexRoute
}

const EksamenRouteChildren: EksamenRouteChildren = {
  EksamenExamIdRoute: EksamenExamIdRoute,
  EksamenIndexRoute: EksamenIndexRoute,
}

const EksamenRouteWithChildren =
  EksamenRoute._addFileChildren(EksamenRouteChildren)

interface OppgaverKapIdRouteChildren {
  OppgaverKapIdSubIdRoute: typeof OppgaverKapIdSubIdRoute
  OppgaverKapIdIndexRoute: typeof OppgaverKapIdIndexRoute
}

const OppgaverKapIdRouteChildren: OppgaverKapIdRouteChildren = {
  OppgaverKapIdSubIdRoute: OppgaverKapIdSubIdRoute,
  OppgaverKapIdIndexRoute: OppgaverKapIdIndexRoute,
}

const OppgaverKapIdRouteWithChildren = OppgaverKapIdRoute._addFileChildren(
  OppgaverKapIdRouteChildren,
)

interface OppgaverRouteChildren {
  OppgaverKapIdRoute: typeof OppgaverKapIdRouteWithChildren
  OppgaverIndexRoute: typeof OppgaverIndexRoute
}

const OppgaverRouteChildren: OppgaverRouteChildren = {
  OppgaverKapIdRoute: OppgaverKapIdRouteWithChildren,
  OppgaverIndexRoute: OppgaverIndexRoute,
}

const OppgaverRouteWithChildren = OppgaverRoute._addFileChildren(
  OppgaverRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EksamenRoute: EksamenRouteWithChildren,
  KunnskapskartRoute: KunnskapskartRoute,
  OppgaverRoute: OppgaverRouteWithChildren,
  ProgrammeringRoute: ProgrammeringRoute,
  RessurserRoute: RessurserRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
